# Generated by Django 4.1.4 on 2023-02-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="notify",),
    ]
