# Generated by Django 4.1.4 on 2023-02-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main_app", "0002_delete_notify"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=50)),
                ("contact", models.IntegerField()),
                ("colg", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
            ],
        ),
    ]
